[2022-09-20T17:16:53.870+0530] {processor.py:153} INFO - Started process (PID=28674) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:16:53.871+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:16:53.871+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:16:53.871+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:16:53.884+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:16:53.884+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:16:53.884+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:16:53.884+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:16:53.884+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:16:53.892+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-20T17:17:31.554+0530] {processor.py:153} INFO - Started process (PID=28961) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:17:31.556+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:17:31.558+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:17:31.557+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:17:31.575+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:17:31.574+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:17:31.575+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:17:31.575+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:17:31.576+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:17:31.594+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-09-20T17:18:05.060+0530] {processor.py:153} INFO - Started process (PID=29107) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:18:05.063+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:18:05.063+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:18:05.063+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:18:05.073+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:18:05.073+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:18:05.073+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:18:05.073+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:18:05.074+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:18:05.081+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-20T17:18:40.709+0530] {processor.py:153} INFO - Started process (PID=29187) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:18:40.712+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:18:40.712+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:18:40.712+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:18:40.725+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:18:40.725+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:18:40.725+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:18:40.725+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:18:40.725+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:18:40.731+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-20T17:19:15.892+0530] {processor.py:153} INFO - Started process (PID=29330) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:19:15.896+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:19:15.897+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:19:15.896+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:19:15.910+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:19:15.909+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:19:15.910+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:19:15.910+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:19:15.910+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:19:15.916+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-09-20T17:20:12.594+0530] {processor.py:153} INFO - Started process (PID=29678) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:20:12.597+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:20:12.598+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:20:12.598+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:20:12.609+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:20:12.608+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:20:12.609+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:20:12.609+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:20:12.609+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:20:12.614+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-20T17:20:49.810+0530] {processor.py:153} INFO - Started process (PID=29741) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:20:49.813+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:20:49.813+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:20:49.813+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:20:49.825+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:20:49.825+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:20:49.825+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:20:49.825+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:20:49.826+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:20:49.832+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:21:23.555+0530] {processor.py:153} INFO - Started process (PID=29856) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:21:23.558+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:21:23.559+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:21:23.559+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:21:23.570+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:21:23.569+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:21:23.570+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:21:23.570+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:21:23.570+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:21:23.576+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-20T17:22:00.836+0530] {processor.py:153} INFO - Started process (PID=30078) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:22:00.840+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:22:00.841+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:22:00.841+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:22:00.852+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:22:00.852+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:22:00.853+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:22:00.853+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:22:00.853+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:22:00.861+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:22:34.527+0530] {processor.py:153} INFO - Started process (PID=30280) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:22:34.531+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:22:34.531+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:22:34.531+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:22:34.543+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:22:34.542+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:22:34.543+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:22:34.543+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:22:34.543+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:22:34.549+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:23:37.258+0530] {processor.py:153} INFO - Started process (PID=30455) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:23:37.261+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:23:37.261+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:23:37.261+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:23:37.271+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:23:37.270+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:23:37.271+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:23:37.271+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:23:37.271+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:23:37.278+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-20T17:24:13.410+0530] {processor.py:153} INFO - Started process (PID=30608) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:24:13.413+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:24:13.414+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:24:13.414+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:24:13.428+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:24:13.428+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:24:13.428+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:24:13.428+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:24:13.428+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:24:13.435+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:24:48.193+0530] {processor.py:153} INFO - Started process (PID=30855) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:24:48.196+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:24:48.197+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:24:48.197+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:24:48.210+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:24:48.209+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:24:48.210+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:24:48.210+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:24:48.210+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:24:48.215+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:25:24.755+0530] {processor.py:153} INFO - Started process (PID=30993) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:25:24.756+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:25:24.757+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:25:24.757+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:25:24.772+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:25:24.772+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:25:24.772+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:25:24.772+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:25:24.772+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:25:24.778+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:26:00.338+0530] {processor.py:153} INFO - Started process (PID=31117) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:26:00.340+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:26:00.341+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:26:00.340+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:26:00.356+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:26:00.356+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:26:00.356+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:26:00.356+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:26:00.356+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:26:00.362+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-09-20T17:26:37.017+0530] {processor.py:153} INFO - Started process (PID=31190) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:26:37.020+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:26:37.021+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:26:37.021+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:26:37.036+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:26:37.036+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:26:37.036+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:26:37.036+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:26:37.036+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:26:37.042+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:27:13.402+0530] {processor.py:153} INFO - Started process (PID=31458) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:27:13.406+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:27:13.407+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:27:13.406+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:27:13.423+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:27:13.423+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:27:13.423+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:27:13.423+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:27:13.424+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:27:13.429+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2022-09-20T17:27:50.334+0530] {processor.py:153} INFO - Started process (PID=31588) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:27:50.337+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:27:50.337+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:27:50.337+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:27:50.351+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:27:50.351+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:27:50.351+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:27:50.351+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:27:50.352+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:27:50.357+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:28:25.220+0530] {processor.py:153} INFO - Started process (PID=31703) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:28:25.222+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:28:25.223+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:28:25.223+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:28:25.237+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:28:25.236+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:28:25.237+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:28:25.237+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:28:25.237+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:28:25.242+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-20T17:29:03.758+0530] {processor.py:153} INFO - Started process (PID=31837) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:29:03.761+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:29:03.762+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:29:03.762+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:29:03.777+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:29:03.776+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:29:03.777+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:29:03.777+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:29:03.777+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:29:03.782+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:29:38.215+0530] {processor.py:153} INFO - Started process (PID=31982) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:29:38.218+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:29:38.219+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:29:38.218+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:29:38.234+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:29:38.233+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:29:38.234+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:29:38.234+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:29:38.234+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:29:38.240+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:30:14.261+0530] {processor.py:153} INFO - Started process (PID=32095) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:30:14.265+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:30:14.266+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:30:14.265+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:30:14.281+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:30:14.280+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:30:14.281+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:30:14.281+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:30:14.281+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:30:14.286+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:30:50.709+0530] {processor.py:153} INFO - Started process (PID=32166) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:30:50.710+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:30:50.711+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:30:50.711+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:30:50.725+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:30:50.725+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:30:50.725+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:30:50.725+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:30:50.725+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:30:50.731+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:31:27.366+0530] {processor.py:153} INFO - Started process (PID=32283) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:31:27.369+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:31:27.369+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:31:27.369+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:31:27.380+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:31:27.380+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:31:27.381+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:31:27.380+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:31:27.381+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:31:27.386+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-20T17:32:03.705+0530] {processor.py:153} INFO - Started process (PID=32473) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:32:03.708+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:32:03.709+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:32:03.709+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:32:03.724+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:32:03.723+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:32:03.724+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:32:03.724+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:32:03.724+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:32:03.729+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:32:38.144+0530] {processor.py:153} INFO - Started process (PID=32608) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:32:38.148+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:32:38.149+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:32:38.148+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:32:38.159+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:32:38.159+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:32:38.159+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:32:38.159+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:32:38.159+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:32:38.164+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-20T17:33:14.203+0530] {processor.py:153} INFO - Started process (PID=32699) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:33:14.206+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:33:14.207+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:33:14.206+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:33:14.223+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:33:14.222+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:33:14.223+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:33:14.223+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:33:14.223+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:33:14.228+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:33:50.147+0530] {processor.py:153} INFO - Started process (PID=32766) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:33:50.150+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:33:50.151+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:33:50.150+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:33:50.167+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:33:50.166+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:33:50.167+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:33:50.167+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:33:50.167+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:33:50.173+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:34:26.704+0530] {processor.py:153} INFO - Started process (PID=32888) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:34:26.707+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:34:26.708+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:34:26.708+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:34:26.720+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:34:26.720+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:34:26.720+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:34:26.720+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:34:26.720+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:34:26.726+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-20T17:35:04.432+0530] {processor.py:153} INFO - Started process (PID=33146) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:35:04.434+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:35:04.435+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:35:04.435+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:35:04.451+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:35:04.451+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:35:04.451+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:35:04.451+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:35:04.452+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:35:04.457+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:35:38.198+0530] {processor.py:153} INFO - Started process (PID=33203) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:35:38.199+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:35:38.199+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:35:38.199+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:35:38.212+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:35:38.211+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:35:38.212+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:35:38.212+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:35:38.212+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:35:38.217+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-20T17:36:17.006+0530] {processor.py:153} INFO - Started process (PID=33358) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:36:17.010+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:36:17.010+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:36:17.010+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:36:17.024+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:36:17.024+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:36:17.024+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:36:17.024+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:36:17.024+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:36:17.030+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:36:52.486+0530] {processor.py:153} INFO - Started process (PID=33422) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:36:52.489+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:36:52.490+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:36:52.490+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:36:52.501+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:36:52.500+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:36:52.501+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:36:52.501+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:36:52.501+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:36:52.510+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:37:29.021+0530] {processor.py:153} INFO - Started process (PID=33696) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:37:29.024+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:37:29.025+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:37:29.025+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:37:29.039+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:37:29.038+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:37:29.039+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:37:29.039+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:37:29.039+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:37:29.047+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:38:16.183+0530] {processor.py:153} INFO - Started process (PID=33838) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:38:16.186+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:38:16.187+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:38:16.187+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:38:16.202+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:38:16.201+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:38:16.202+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:38:16.202+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:38:16.202+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:38:16.208+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:38:53.908+0530] {processor.py:153} INFO - Started process (PID=33901) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:38:53.911+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:38:53.912+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:38:53.912+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:38:53.922+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:38:53.922+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:38:53.922+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:38:53.922+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:38:53.922+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:38:53.928+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-20T17:39:27.086+0530] {processor.py:153} INFO - Started process (PID=34024) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:39:27.089+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:39:27.090+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:39:27.090+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:39:27.105+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:39:27.104+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:39:27.105+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:39:27.105+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:39:27.105+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:39:27.110+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:40:04.238+0530] {processor.py:153} INFO - Started process (PID=34185) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:40:04.241+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:40:04.242+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:40:04.242+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:40:04.253+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:40:04.253+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:40:04.253+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:40:04.253+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:40:04.253+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:40:04.259+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-20T17:40:39.305+0530] {processor.py:153} INFO - Started process (PID=34292) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:40:39.308+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:40:39.309+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:40:39.308+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:40:39.324+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:40:39.323+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:40:39.324+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:40:39.324+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:40:39.324+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:40:39.329+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:41:17.363+0530] {processor.py:153} INFO - Started process (PID=34409) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:41:17.366+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:41:17.367+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:41:17.367+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:41:17.382+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:41:17.382+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:41:17.382+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:41:17.382+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:41:17.382+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:41:17.388+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:42:13.355+0530] {processor.py:153} INFO - Started process (PID=34562) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:42:13.357+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:42:13.358+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:42:13.358+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:42:13.373+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:42:13.372+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:42:13.373+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:42:13.373+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:42:13.373+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:42:13.378+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-09-20T17:45:44.727+0530] {processor.py:153} INFO - Started process (PID=34956) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:45:44.730+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:45:44.731+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:45:44.731+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:45:44.748+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:45:44.748+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:45:44.749+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:45:44.749+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:45:44.749+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:45:44.760+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2022-09-20T17:46:39.339+0530] {processor.py:153} INFO - Started process (PID=35086) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:46:39.342+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:46:39.343+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:46:39.342+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:46:39.357+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:46:39.357+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:46:39.357+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:46:39.357+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:46:39.358+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:46:39.363+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:47:15.422+0530] {processor.py:153} INFO - Started process (PID=35321) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:47:15.425+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:47:15.426+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:47:15.426+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:47:15.442+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:47:15.442+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:47:15.442+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:47:15.442+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:47:15.442+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:47:15.448+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:47:52.578+0530] {processor.py:153} INFO - Started process (PID=35425) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:47:52.578+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:47:52.579+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:47:52.579+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:47:52.586+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:47:52.586+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:47:52.586+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:47:52.586+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:47:52.587+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:47:52.592+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-09-20T17:48:29.785+0530] {processor.py:153} INFO - Started process (PID=35525) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:48:29.788+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:48:29.789+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:48:29.789+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:48:29.805+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:48:29.804+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:48:29.805+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:48:29.805+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:48:29.805+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:48:29.810+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-09-20T17:49:07.667+0530] {processor.py:153} INFO - Started process (PID=35655) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:49:07.669+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:49:07.670+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:49:07.670+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:49:07.686+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:49:07.685+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:49:07.686+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:49:07.686+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:49:07.686+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:49:07.691+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-20T17:49:43.683+0530] {processor.py:153} INFO - Started process (PID=35724) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:49:43.685+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:49:43.685+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:49:43.685+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:49:43.697+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:49:43.697+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:49:43.697+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:49:43.697+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:49:43.697+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:49:43.703+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-20T17:50:21.107+0530] {processor.py:153} INFO - Started process (PID=35832) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:50:21.110+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:50:21.111+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:50:21.111+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:50:21.124+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:50:21.124+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:50:21.124+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:50:21.124+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:50:21.125+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:50:21.130+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-09-20T17:50:57.952+0530] {processor.py:153} INFO - Started process (PID=35938) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:50:57.955+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:50:57.956+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:50:57.956+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:50:57.969+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:50:57.968+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:50:57.969+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:50:57.969+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:50:57.969+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:50:57.976+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-20T17:51:33.882+0530] {processor.py:153} INFO - Started process (PID=36005) to work on /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:51:33.885+0530] {processor.py:640} INFO - Processing file /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-20T17:51:33.885+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:51:33.885+0530] {dagbag.py:508} INFO - Filling up the DagBag from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:51:33.901+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:51:33.900+0530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-20T17:51:33.901+0530] {logging_mixin.py:115} INFO - [2022-09-20T17:51:33.901+0530] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-20T17:51:33.901+0530] {processor.py:652} WARNING - No viable dags retrieved from /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-20T17:51:33.911+0530] {processor.py:161} INFO - Processing /home/sayone/This PC/SayOne Technologies/Works/airflow_new/Airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
